apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hpgrahsl-poi-backend-app-dev
  annotations:
    argocd/app-name: hpgrahsl-poi-backend-app-dev
    backstage.io/kubernetes-id: hpgrahsl-poi-backend-app
    backstage.io/kubernetes-namespace: hpgrahsl
    backstage.io/techdocs-ref: dir:.
    github.com/project-slug: rhdh-aro24/hpgrahsl-backend
    janus-idp.io/tekton-enabled: 'true'
  tags:
    - java
    - quarkus
    - maven
    - workshop
  links:
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/dev-pipelines/ns/hpgrahsl/
      title: Pipelines
      icon: web
    - url: https://console-openshift-console.apps.kovj5vhc.eastus.aroapp.io/k8s/ns/hpgrahsl/deployments/hpgrahsl-poi-backend-app
      title: Deployment
      icon: web
    - url: https://devspaces.apps.kovj5vhc.eastus.aroapp.io/#https://github.com/rhdh-aro24/hpgrahsl-backend?che-editor=che-incubator/che-code/latest&devfilePath=.devfile-vscode.yaml
      title: OpenShift Dev Spaces (VS Code)
      icon: web
spec:
  type: service
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hpgrahsl
  providesApis:
    - backend-api-hpgrahsl
---
apiVersion: backstage.io/v1alpha1
kind: System
metadata:
  name: workshop-system-hpgrahsl
  tags:
    - backstage
    - janus-idp
    - openshift
    - workshop
    - rh-summit
spec:
  owner: "user:default/hpgrahsl"
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: backend-api-hpgrahsl
  description: API surface used by workshop attendees to initialize and load parks data
  links:
    - url: http://hpgrahsl-poi-backend-app-hpgrahsl.apps.kovj5vhc.eastus.aroapp.io/q/swagger-ui
      title: Swagger UI
      icon: web
    - url: https://github.com/rhdh-aro24/hpgrahsl-backend/tree/main/src/main/resources/META-INF/openapi.yaml
      title: API Spec
      icon: code
spec:
  type: openapi
  lifecycle: production
  owner: "user:default/hpgrahsl"
  system: workshop-system-hpgrahsl
  definition:
    $text: https://github.com/rhdh-aro24/hpgrahsl-backend/tree/main/src/main/resources/META-INF/openapi.yaml
